
platform:
  - x64

environment:
  matrix:
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - where sleep
  - where marked
  - where uuid

test_script:
  # run tests
  - npm test

build: off
